# ── Notes ─────────────────────────────
# For destination, config:
# capitalized name (1st letter) denotes a global config or destination

# ── Main Toml ─────────────────────────
[global]
deep = true
use_gitignore = false
keep_historic = false
# ignore_method: dotstrike(managed through dotstrike) | toml | gitignore(format)
#     - gitignore is the lowest priority dev-wise
#     - dotstrike & toml will be formatted the same
ignore_method = 'dotstrike'                          #file|dotstrike|toml
ignore_file = '.\dsignore'
primary_destination_dir = '~\.config\dotstrike\apps'
second_drive_dir = 'D:\dotstrike\'
backup_global = false
[global.defaults]


[[sets]] # groups
name = "GLOBAL"
apps = ["nvim"]


[[apps]]
name = "nvim"
app_path = '' # optional

config_names = ['main']
# fully separate configs and refer by name? or do it differently?
destination_names = ['Main']

[[apps]]
name = "wezterm"
config_names = ['main']
destination_names = ['Main']

[[destination]]
name = "Main"
path = 'C:\dev\.config\dotstrike'
# appname_folder: apps will be stored in subdirectories named [ app.name ]
appname_folder = true

global.configs = [
   { name = 'nvim__main', dir = '~\AppData\Local\nvim' },
   { name = 'wezterm__main', dir = '~\.config\wezterm' },
]
