[global]
targetPath = '~/.config/dotstrike/store'

[global.prefs]
keepRepo = true
keepHidden = true
storedata.sourcedir = true
globalTarget = true

[global.data]
[[cfgs]]
alias = 'wezterm'
sources = ['~/.config/wezterm']
targets = ['@GLOBAL']

[[cfgs]]
alias = 'nvim'
sources = ['~/AppData/Local/nvim']
targets = ['@GLOBAL']
