storagePath = '~/.config/dotstrike/store'

[prefs]
keepRepo = true
keepHidden = true
#storedata.sourcedir = true
globalTarget = true
SelectedCFG = 1 # index of cfg that is currently selected

[[cfgs]]
alias = 'wezterm'
sources = [{alias = 'wezterm:s0',path = '~/.config/wezterm', ptype = 1,abspath='C:/Users/derek/.config/wezterm'}]
targets = [{alias = '@GLOBAL@'}]

[[cfgs]]
alias = 'nvim'
sources = [{alias = 'nvim:s0',path='~/AppData/Local/nvim', ptype=1,abspath='C:/Users/derek/AppData/Local/nvim'}]
targets = [{alias = '@GLOBAL@'}]
ignores=['_xtra/']
