storagePath = '~/.config/dotstrike/store'

[prefs]
keepRepo = true
keepHidden = true
globalTarget.enabled = true
globalTarget.path = 'c:/dev/.config/configSync'
SelectedSpec = 1                                # index of cfg that is currently selected

[[specs]]
alias = 'wezterm'
sources = [
    { alias = 'wezterm:s0', path = '~/.config/wezterm', ptype = 1, abspath = 'C:/Users/derek/.config/wezterm' },
]
targets = [{ alias = '@GLOBAL@' }]

[[specs]]
alias = 'nvim'
sources = [
    { alias = 'nvim:s0', path = '~/AppData/Local/nvim', ptype = 1, abspath = 'C:/Users/derek/AppData/Local/nvim' },
]
targets = [{ alias = '@GLOBAL@' }]
ignores = ['_xtra/']
