SelectedSpec = 1

[prefs]
KeepRepo = true
KeepHidden = true
GlobalTarget = true
GlobalTargetPath = 'c:/dev/.config/configSync'

[[specs]]
alias = 'wezterm'
sources = [
    { alias = 'wezterm:s0', path = '~/.config/wezterm', ptype = 1, abspath = 'C:/Users/derek/.config/wezterm' },
]
targets = [{ alias = '@GLOBAL@' }]

[[specs]]
alias = 'nvim'
sources = [
    { alias = 'nvim:s0', path = '~/AppData/Local/nvim', ptype = 1, abspath = 'C:/Users/derek/AppData/Local/nvim' },
]
targets = [{ alias = '@GLOBAL@' }]
ignores = ['_xtra/']
