SelectedSpec = 0

[prefs]
KeepRepo = true
KeepHidden = true
GlobalTarget = true

[[specs]]
alias = "nvim"
overrideOn = false
Ctype = 1

[[specs.sources]]
alias = "nvim-config"
abspath = ""
ptype = 0
ctype = 2
Parent = "nvim"

[[specs.targets]]
alias = ""
abspath = ""
path = "@GLOBAL@"
ptype = 0
ctype = 3
Parent = "nvim"
[specs.overrides]
KeepRepo = false
KeepHidden = false
GlobalTarget = false
GlobalTargetPath = ""

[[specs]]
alias = "wezterm"
overrideOn = false
Ctype = 1

[[specs.sources]]
alias = ""
abspath = ""
path = "~\\.config\\wezterm"
ptype = 0
ctype = 2
Parent = "wezterm"

[[specs.targets]]
alias = ""
abspath = ""
path = "@GLOBAL@"
ptype = 0
ctype = 3
Parent = "wezterm"
[specs.overrides]
KeepRepo = false
KeepHidden = false
GlobalTarget = false
GlobalTargetPath = ""
